# Generated by Django 5.0.6 on 2024-05-30 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gitclusterapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClusterDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cluster_id', models.CharField(max_length=100)),
                ('cluster_name', models.CharField(max_length=100)),
                ('connection_id', models.CharField(max_length=100)),
                ('user_id', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=100)),
                ('backend_key', models.CharField(max_length=100)),
                ('cluster_version', models.CharField(max_length=100)),
                ('disk_size', models.IntegerField()),
                ('min_size', models.IntegerField()),
                ('max_size', models.IntegerField()),
                ('desired_size', models.IntegerField()),
                ('instance_type', models.CharField(max_length=100)),
                ('vpc_name', models.CharField(max_length=100)),
                ('vpc_id', models.CharField(max_length=100)),
                ('public_subnets', models.JSONField()),
                ('private_subnets', models.JSONField()),
                ('public_subnet_cidr', models.JSONField()),
                ('private_subnet_cidr', models.JSONField()),
                ('domain_names', models.JSONField()),
                ('cluster_endpoint', models.CharField(max_length=100)),
                ('has_created', models.BooleanField()),
                ('lb_url', models.CharField(max_length=100)),
            ],
        ),
    ]
